### ISSUE TITLE
Cards are missing informations

### ISSUE THREAD

**Issue by soanvig** [Tressley/hpjson#1]
All cards should contain all informations (like cost: 0), so every card object contains full set of informations and no unknown 'default values'. This way every card will be standardized which is requirement for JSON API.

**Comment by Tressley** [comment]
Does this mean **every** card, including Lessons, should include: `powerCost, flavorText, dmgEachTurn, health`?

**Comment by soanvig** [comment]
Good question. I didn't think about that.

Well, it could be set to `null`, but I think it is okey that there are no values. It would be the same.

However **must-have** is my #2 issue. Then `Lesson` would be `1`, character `2` etc. Easy to distinguish.

**Comment by Tressley** [comment]
I think defaulting to `null` is fine as those will not return results on given definitions. Closing this issue.

**Comment by Tressley** [comment]
Just a test.
