### ISSUE TITLE
Cards data issues

### ISSUE THREAD

**Issue by jsjohann** [Tressley/hpjson#13]
- _Draco Malfoy 3a_ is rare, not foil premium
- _Professor Snape_ misses Healing subtype
- _Giant Tarantula_ costs 1
- _Snape's Question_ costs 3
- _Peeves_ misses Ghost subtype
- _Muddy Practise_ misses it's ability
- _Photo Album_ should be an item
- _Broken Wand_ misses Wand subtype

**Comment by Tressley** [comment]
Fixed with the most recent update.
