### ISSUE TITLE
Issues on cards data

### ISSUE THREAD

**Issue by jsjohann** [Tressley/hpjson#14]
- _Beetle Eyes_ missing subtype "Beetle Eyes"
- _Eel Eyes_ missing subtype "Eel Eyes"
- _Muddy Practise_ missing action
- _Broken Wand_ missing subtype "Wand"

**Comment by jsjohann** [comment]
The issue on Muddy Practise is more of an implementation issue for Irma or Accio.

**Comment by Tressley** [comment]
Fixed in #15
