### ISSUE TITLE
Alchemy is listed as a rare instead of uncommon

### ISSUE THREAD

**Issue by perezdev** [Tressley/hpjson#16]
Fixed this issue in Accio. But the data came from hpJSON:

![image](https://user-images.githubusercontent.com/3408775/88757339-60706900-d12b-11ea-8500-cec4ada9a1a9.png)

![image](https://user-images.githubusercontent.com/3408775/88757372-7120df00-d12b-11ea-814a-1b0b70df1f47.png)

**Comment by Tressley** [comment]
Fixed in 4bed4cf
