### ISSUE TITLE
New Slytherin Seeker text update.

### ISSUE THREAD

**Issue by StefanGiovanni** [Tressley/hpjson#18]
"description":"Do 5 damage to an opponent. If there is a Match is in play, you may have that opponent choose 1 of their Creatures in play and discard it.",

Need to remove extra "is" after Match. Should be—

"description":"Do 5 damage to an opponent. If there is a Match in play, you may have that opponent choose 1 of their Creatures in play and discard it.",

**Comment by Tressley** [comment]
Fixed in cee362c.
