### ISSUE TITLE
Id-fied shared values

### ISSUE THREAD

**Issue by soanvig** [Tressley/hpjson#2]
Values of fields like 'unique', 'holo', 'rare' and similar, should be id-fied.

i.e.
```
non_unique = 0
unique = 1

holo = 4
rare = 3
common = 0
```
etc.

**Comment by Tressley** [comment]
What if a card has a rare and holo version?

**Comment by Tressley** [comment]
Can you elaborate more as to why this is necessary? If you reference [MTGJSON](https://raw.githubusercontent.com/mtgjson/mtgjson/master/json/10E.json), none of their fields are defined this way.

**Comment by soanvig** [comment]
Well, maybe it's not that necessary, but it is reference-structure coming from databases:
```json
// records
{
   id: 1,
   type: 2,
}
```

```json
// types
{
   id: 2,
   name: 'character'
}
```

It is just more elastic to use.  Imagine, we need to change the name of 'character' type. We can just do it in `types.json` table. Otherwise we would need to do it in all files.
The downside of this is not complete informations in one JSON.

**Comment by soanvig** [comment]
But I've checked and thought twice, and basically I think we can forget about that. 

See http://jsonapi.org/. I think those JSON could be written with this specification.

While in fact this specification would be convenient, it may be overkill for such a simple structures.

**Comment by Tressley** [comment]
Great! Thanks for the information. To be honest, I don't imagine us changing too much of the information (considering the game has been out of print for 15 years. 😄 ) I think we're okay with the current structure of the file. I'll close this issue as well.
