### ISSUE TITLE
Swallowed Snitch lists the artist as 

### ISSUE THREAD

**Issue by perezdev** [Tressley/hpjson#20]
https://github.com/Tressley/hpjson/blob/cee362c33d38133f77cec13899220d88e416a8cf/sets/heir%20of%20slytherin/cards.json#L294

The JSON shows (c)JoeriVanRoyen instead of Joeri Van Royen as it does on the card:

![image](https://user-images.githubusercontent.com/3408775/95403519-139dd100-08d8-11eb-865b-f00ec7b699ae.png)

**Comment by Tressley** [comment]
Fixed in 7532553
