### ISSUE TITLE
Flavour text update

### ISSUE THREAD

**Issue by MHP47** [Tressley/hpjson#25]
DA No.10 - Gringotts

Flavour text currently reads: `"flavorText":"'Enter stranger, but take heed of what awaits the sing of greed, ...' — Gringotts engraving",`

Should be: `"flavorText":"'Enter stranger, but take heed of what awaits the sin of greed, ...' — Gringotts engraving",`

`sing` should be `sin`

**Comment by Tressley** [comment]
Fixed in 9700922.
