### ISSUE TITLE
Better structure of JSON

### ISSUE THREAD

**Issue by soanvig** [Tressley/hpjson#3]
My proposal of structure comes from http://jsonapi.org/:

`/api/cards` - would return all cards
`/api/cards/[set]` - would return all cards of set
`/api/cards/[set]/[id]` - would return one card of set

Every set has it's individual id sequence, then card's id isn't unique
While `set + id` makes unique pair, it is hard to maintain.

The best idea would be to create database of `cards` where each card would have it's unique `id`, `set` binding, and `number` (id in set) (besides informations about card itself).

The best idea would be to create database of `cards` where each card would have it's unique `id`, `set` binding, and `number` (id in set) (besides informations about card itself).

Final JSON of `/api/cards`:

```json
{
	"meta": {
		"cardsNumber": 12
	},
	"data": [
		{
			"id": "0",
			"type": "cards",
			"attributes": {
				"id": 1,
				"set_id": 0,
				"power": 6,
				"lesson_id": 2,
				// ....
			}
		},
		{
			"id": "1",
			"type": "cards",
			"attributes": {
				"id": 2,
				"set_id": 0,
				"power": 4,
				"lesson_id": null,
				// ....
			}
		}
	]
}
```

To avoid implementing whole *relationships* stuff, informations about relations (`lesson_id = 1 ~ 'Charms'`) can be retrieved by app in initial request.

It is easy to convert programmatically actual structure to new one.

**Comment by Tressley** [comment]
So, you'd want to have a universal file that defines `set` by 1-5, `lessonType` by 1-5, etc?

**Comment by soanvig** [comment]
First, we gonna have no json files but database (which in fact is similar). It can be simplest nosql database.

Secondly, we gonna have table `cards` which the structure I've described above.

Thirdly, we gonna have on table called `relations` which will describe sets, lessons and other values, as "numbers".
